// app/src/components/TwitchClip.tsx
import React from "react";

export function TwitchClip({ clip_id }: { clip_id: string }) {
  return (
    <span>
      <iframe
        src={`https://clips.twitch.tv/embed?clip=${clip_id}&parent=${window.location.hostname}`}
        width="100%"
        className="aspect-video"
        allowFullScreen={true}
      />
    </span>
  );
}

// front/components/TwitchClip.vue
<script setup>
const props = defineProps({
    clipId: String
})
const parent = ref('');
onMounted(() => {
    parent.value = window.location.hostname;
})
const vidSource = computed(() => `https://clips.twitch.tv/embed?clip=${props.clipId}&parent=${parent.value}`);


</script>

<template>

<iframe :src="vidSource" v-if="vidSource && parent" frameborder="0" allowfullscreen="true" scrolling="no"
            height="378" width="620" />
</template>
